name: Vitest
on: [push, workflow_dispatch]
jobs:
  vitest-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install
      - run: pnpm docs-build
      - run: pnpm test
